spring:
  application:
    #服务名
    name : api-gateway
server:
  port: 5555

zuul:
  routes:
      api-a-url:
          #访问路径path
          path: /api-a-url/**
          #将访问路径path转发到url上
          url: http://localhost:9001
      api-b-url:
          #访问路径path
          path: /api-b/**
          #将访问路径path转发到服务上
          service-id: hello-service
      #zuul.routes.api-c-url.path和zuul.routes.api-c-url.serviceId等同于zuul.routes.feign-consumer=/api-c/**
      api-c-url:
          #访问路径path
          path: /api-c/**
          #将访问路径path转发到服务上
          service-id: feign-consumer
      api-d-url:
          #访问路径path
          path: /api-d/**
          #将访问路径path本地跳转到api-a-url上
          url: forward:/tt
  #不创建默认路由配置
  ignored-services: hello-service
  #指定接口不被路由
  ignored-patterns: /**/hello7/**
eureka:
  client:
    serviceUrl:
      #defaultZone，指定访问地址
      defaultZone: http://localhost:1111/eureka/