spring:
  application:
    #服务名
    name : hello-service
eureka:
  client:
    serviceUrl:
      #指明注册中心
      #defaultZone  : http://localhost:1111/eureka/
      defaultZone  : http://peer1:1111/eureka/,http://peer2:1112/eureka/

