spring:
  application:
    #服务名
    name : config-server
  cloud:
    config:
      server:
        git:
          #配置文件所在仓库，有.git
          uri: https://github.com/wxbabyboy1/spring-cloud-test-config-server.git
          #这是直接https那个网址
          #uri: https://github.com/wxbabyboy1/spring-cloud-test-config-server
          #这是本地的git仓库，我找的是这个本地git项目。windows多个/，linux没有多个/
          #uri: file:///D:/workspace/spring-cloud-test
          #配置文件所在根目录
          search-paths: spring_cloud_in_action/config-repo
          #这是本地对应的那个根目录
          #search-paths: config-server/config-repo
          #账号
          username: wxbabyboy1
          #密码
          password: mscommand12345

server:
  port: 7001
