server:
    port : 1112

eureka:
  instance:
    hostname : peer2
  client:
    #自己是注册中心，下面不注册自己，选择false
    registerWithEureka : false
    #自己是注册中心，下面就不遍历注册了，选择false
    fetchRegistry : false
    serviceUrl:
      #defaultZone，指定访问地址
      defaultZone: http://peer1:1111/eureka/

